services:
  - type: web
    name: website-builder-backend
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: website-builder-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: website-builder-db
    plan: free
    databaseName: website_builder
    user: website_builder_admin
